/**
 * Teaching staff, transcribed from the official AEBAS staff list (PDF).
 * Rendered as HTML tables on the Faculty page, grouped by department.
 * (The original scanned PDF remains available to download alongside.)
 */

import type { Faculty } from "@/lib/supabase/types";

export type StaffMember = { name: string; designation: string };
export type StaffDept = { slug: string; name: string; members: StaffMember[] };

/** Group DB faculty rows into department blocks, preserving order. */
export function groupDbFaculty(faculty: Faculty[]): StaffDept[] {
  const order: string[] = [];
  const byDept: Record<string, StaffMember[]> = {};
  for (const f of faculty) {
    const dept = f.department || "Faculty";
    if (!byDept[dept]) {
      byDept[dept] = [];
      order.push(dept);
    }
    byDept[dept].push({ name: f.name, designation: f.designation || "" });
  }
  return order.map((name) => ({ slug: name, name, members: byDept[name] }));
}

const P = "Professor";
const HOD = "Professor & HOD";
const AS = "Associate Professor";
const AP = "Assistant Professor";
const SR = "Senior Resident";
const JR = "Junior Resident";
const TU = "Tutor";

export const TEACHING_STAFF: StaffDept[] = [
  {
    slug: "anatomy",
    name: "Anatomy",
    members: [
      { name: "Dr. Dhannya Binoy", designation: HOD },
      { name: "Dr. Kalpana Rajendra Gaikwad", designation: AS },
      { name: "Dr. Salahuddin Azeemuddin Patel", designation: AS },
      { name: "Dr. Monika Soni", designation: AP },
      { name: "Dr. Saikarthik J", designation: AP },
      { name: "Dr. Ankit Purushottam Biyani", designation: TU },
      { name: "Dr. Arun Subhash Jain", designation: TU },
      { name: "Dr. Arvind Asaram Aghao", designation: TU },
      { name: "Dr. Narendra Sanjay Sarode", designation: TU },
      { name: "Dr. Nitin Bansi Jadhao", designation: TU },
      { name: "Dr. Prashant Ramnath Kanade", designation: TU },
      { name: "Dr. Shubham Parmeshwar Chaudhari", designation: TU },
      { name: "Dr. Vaibhav Shivaji Akangire", designation: TU },
      { name: "Dr. Shivani Dattatray Yewale", designation: TU },
    ],
  },
  {
    slug: "physiology",
    name: "Physiology",
    members: [
      { name: "Dr. Barkat Ali Abdul Ali Thobani", designation: HOD },
      { name: "Dr. Neelima Jaykumar Bhandarkar", designation: P },
      { name: "Dr. Priya Nitin Samal", designation: AS },
      { name: "Dr. Saraswathi", designation: AP },
      { name: "Dr. Sneha Vitthal Chopade", designation: AP },
      { name: "Dr. Akshay Gajanan Ulhamale", designation: TU },
      { name: "Dr. Ashwin Vijay Chamediya", designation: TU },
      { name: "Dr. Gunwant Shankar Shelke", designation: TU },
      { name: "Dr. Komal Dhanraj Rathi", designation: TU },
      { name: "Dr. Gaurav Gajanan Lonkar", designation: TU },
      { name: "Dr. Nikhil Gajanan Gite", designation: TU },
      { name: "Dr. Prashant Ajay Ingle", designation: TU },
      { name: "Dr. Sapana Mahendra Chandak", designation: TU },
    ],
  },
  {
    slug: "biochemistry",
    name: "Bio Chemistry",
    members: [
      { name: "Dr. Srushtee Bipin Jibhkate", designation: HOD },
      { name: "Dr. Amit Hiralal Asalkar", designation: AS },
      { name: "Dr. Chiruvella Sravani", designation: AP },
      { name: "Dr. Seema Akhil Agarwal", designation: AP },
      { name: "Dr. Chetan Mahadeo Satote", designation: TU },
      { name: "Dr. Gopal Dinesh Nawgaje", designation: TU },
      { name: "Dr. Prathamesh Ramesh Akhare", designation: TU },
      { name: "Dr. Pratiksha Ambadas Aghao", designation: TU },
      { name: "Dr. Sakshi Sushil Rathi", designation: TU },
      { name: "Dr. Shraddha Mayur Agrawal", designation: TU },
      { name: "Dr. Yogita Panjab Shejol", designation: TU },
    ],
  },
  {
    slug: "microbiology",
    name: "MicroBiology",
    members: [
      { name: "Dr. Mayuri Nikhil Mahajan", designation: P },
      { name: "Dr. Anjali Lalit Raut", designation: AS },
      { name: "Dr. Sonali Mangesh Choudhari", designation: AS },
      { name: "Dr. Pankaj Vishwakarma", designation: AP },
      { name: "Dr. Rutuja Avinash Dongare", designation: AP },
      { name: "Dr. Vidya Nagesh Bhosale", designation: AP },
      { name: "Dr. Suvarna Samir Bhopale", designation: TU },
      { name: "Dr. Madhvik Sanjay Lohiya", designation: TU },
      { name: "Dr. Om Vijay Lahane", designation: TU },
      { name: "Dr. Nikhil Shridhar Jaybhaye", designation: TU },
      { name: "Dr. Rohit Ramesh Patil", designation: TU },
      { name: "Dr. Pratiksha Nagsen Wankhade", designation: TU },
      { name: "Dr. Shruti Vikas Shinde", designation: TU },
    ],
  },
  {
    slug: "pharmacology",
    name: "Pharmacology",
    members: [
      { name: "Dr. Vivek Lal", designation: P },
      { name: "Dr. Chetan Shankarrao Urade", designation: AS },
      { name: "Dr. Rahul Tilakchand Khobragade", designation: AS },
      { name: "Dr. Akhil Bharat Agarwal", designation: AP },
      { name: "Dr. Arpit Vallabhbhai Vachhani", designation: AP },
      { name: "Dr. Florence Bhava", designation: AP },
      { name: "Dr. Nilesh Shivaji Kute", designation: TU },
      { name: "Dr. Nitin Prakash Sanap", designation: TU },
      { name: "Dr. Rameshwar Balaji Dalvi", designation: TU },
      { name: "Dr. Rushikesh Sudhakar Lahane", designation: TU },
      { name: "Dr. Santosh Kalyanrao Gawade", designation: TU },
      { name: "Dr. Shubham Uddhav Nagre", designation: TU },
      { name: "Dr. Vaibhav Subhash Shinde", designation: TU },
    ],
  },
  {
    slug: "pathology",
    name: "Pathology",
    members: [
      { name: "Dr. Suchita Chetan Padia", designation: HOD },
      { name: "Dr. Anandkumar Chordiya", designation: AS },
      { name: "Dr. Bramhananda Ramrao Tale", designation: AS },
      { name: "Dr. Preethi Tushar Charkha", designation: AS },
      { name: "Dr. Dnyaneshwar Ashok Doifode", designation: AP },
      { name: "Dr. Kavita Yogesh Kolamkar", designation: AP },
      { name: "Dr. Shyamkumar Haribhau Nemade", designation: AP },
      { name: "Dr. Pratibha Tejrao Shinde", designation: SR },
      { name: "Dr. Shwetali Ramesh Akhare", designation: SR },
      { name: "Dr. Snehal Rameshsing Rajput", designation: SR },
      { name: "Dr. Akshay Anandrao Dolarkar", designation: TU },
      { name: "Dr. Sanket Keshaorao Nagre", designation: TU },
      { name: "Dr. Shruti Sagar Idhol", designation: TU },
      { name: "Dr. Vaishnavi Dinkar Rathod", designation: TU },
      { name: "Dr. Vikas Anandrao Nagargoje", designation: TU },
    ],
  },
  {
    slug: "community-medicine",
    name: "PSM (Community Medicine)",
    members: [
      { name: "Dr. Prashil Prakashrao Jumade", designation: HOD },
      { name: "Dr. Gokul Kumar K", designation: AS },
      { name: "Dr. Swapnil Wamanrao Malkhede", designation: AS },
      { name: "Dr. Saniya Sk. Shafi Qureshi", designation: AP },
      { name: "Dr. Sunil Marutirao Bhadkumbe", designation: AP },
      { name: "Dr. Amol Gowardhan Dakhare", designation: "Statistician" },
      { name: "Dr. Ambarish Ghansham Mandhane", designation: TU },
      { name: "Dr. Ashish Gajanan Khandare", designation: TU },
      { name: "Dr. Atul Girdharilal Singhania", designation: TU },
      { name: "Dr. Atul Sureshrao Junghare", designation: TU },
      { name: "Dr. Sarvesh Pravin Bhansali", designation: TU },
      { name: "Dr. Umesh Narsing Jadhao", designation: TU },
    ],
  },
  {
    slug: "forensic-medicine",
    name: "Forensic Medicine (FMT)",
    members: [
      { name: "Dr. Shailendra Hemant Anande", designation: AS },
      { name: "Dr. Purushottam Madhukar Khade", designation: AP },
      { name: "Dr. Akshay Madhusudan Toshniwal", designation: TU },
      { name: "Dr. Ashutosh Vijay Deshmukh", designation: TU },
      { name: "Dr. Pranali Madhusudan Toshniwal", designation: TU },
      { name: "Dr. Prashant Ramkrushn Wayal", designation: TU },
      { name: "Dr. Saurav Gajanan Tale", designation: TU },
      { name: "Dr. Shubham Shriram Ingle", designation: TU },
    ],
  },
  {
    slug: "general-medicine",
    name: "General Medicine",
    members: [
      { name: "Dr. Shankar Baliram Wankhade", designation: HOD },
      { name: "Dr. Yuvraj Vasantrao Mhaske", designation: P },
      { name: "Dr. Amit Chandrakant Rathi", designation: AS },
      { name: "Dr. Bharat Murlidhar Pangole", designation: AS },
      { name: "Dr. Santosh Suresh Saoji", designation: AS },
      { name: "Dr. Ashish Janardan Changade", designation: AP },
      { name: "Dr. Harish Ramesh Darak", designation: AP },
      { name: "Dr. Mahesh Ramdas Ohar", designation: AP },
      { name: "Dr. Sagar Ravindra Idhol", designation: AP },
      { name: "Dr. Yogesh Gajanan Kolamkar", designation: AP },
      { name: "Dr. Yogeshwar Sureshrao Mukund", designation: AP },
      { name: "Dr. Amol Bhagwanrao Khavane", designation: SR },
      { name: "Dr. Dhananjay Samadhan Marode", designation: SR },
      { name: "Dr. Swapnil Dinkar Sarode", designation: SR },
      { name: "Dr. Tushar Kamalkishor Charkha", designation: SR },
      { name: "Dr. Akshay Dnyanba Gilwarkar", designation: JR },
      { name: "Dr. Ashwin Manohar Khandare", designation: JR },
      { name: "Dr. Bhushan Pravin Mallawat", designation: JR },
      { name: "Dr. Ruturaj Narayan Nagargoje", designation: JR },
      { name: "Dr. Neeraj Sanjay Thakur", designation: JR },
      { name: "Dr. Pranav Sanjay Salunke", designation: JR },
      { name: "Dr. Prashant Vishnu Tejankar", designation: JR },
      { name: "Dr. Pravin Vaijinath Parne", designation: JR },
      { name: "Dr. Rahul Gajananrao Sonune", designation: JR },
      { name: "Dr. Shantanu Diliprao Joshi", designation: JR },
      { name: "Dr. Tushar Vijay Pandav", designation: JR },
      { name: "Dr. Vaibhav Sukhadeo Thakare", designation: JR },
      { name: "Dr. Vinit Panditrao Deshmukh", designation: JR },
    ],
  },
  {
    slug: "pediatrics",
    name: "Pediatrics",
    members: [
      { name: "Dr. Chetan Bhagwandas Padia", designation: HOD },
      { name: "Dr. Nikhil Madhav Mahajan", designation: P },
      { name: "Dr. Vishwanath Narayan Dighole", designation: AS },
      { name: "Dr. Anil Rajendra Tapdiya", designation: AP },
      { name: "Dr. Bhagyashree Macchindra Jagtap", designation: AP },
      { name: "Dr. Shailee Rasikchandra Patel", designation: AP },
      { name: "Dr. Mansi Shah", designation: AP },
      { name: "Dr. Shailesh Dilip Jain", designation: AP },
      { name: "Dr. Abolee Jalandar Pansare", designation: SR },
      { name: "Dr. Amit Shantilal Bora", designation: SR },
      { name: "Dr. Ashish Hanwantrao Narwade", designation: SR },
      { name: "Dr. Samir Ashokrao Bhopale", designation: SR },
      { name: "Dr. Nilesh Ashok Sanap", designation: SR },
      { name: "Dr. Pravin Khushalrao Gawai", designation: SR },
      { name: "Dr. Sharad Shamsundar Lakhotiya", designation: SR },
      { name: "Dr. Vinayak Shivaji Changade", designation: SR },
      { name: "Dr. Vinod Kishor Ramchandani", designation: SR },
      { name: "Dr. Vivek Chandrashekhar Kapse", designation: SR },
      { name: "Dr. Aniket Rameshwar Kewat", designation: JR },
    ],
  },
  {
    slug: "dermatology",
    name: "Dermatology (Skin / DVL)",
    members: [
      { name: "Dr. Rajesh Omprakash Kedia", designation: HOD },
      { name: "Dr. Sagar Subhash Taley", designation: AS },
      { name: "Dr. Areha Jain", designation: AP },
      { name: "Dr. Saurabh Santosh Sarda", designation: AP },
      { name: "Dr. Shivani Munnalal Agrawal", designation: SR },
      { name: "Dr. Yogeshree Nikhil Kanase", designation: SR },
      { name: "Dr. Surekha Pramod Jadhav", designation: JR },
    ],
  },
  {
    slug: "psychiatry",
    name: "Psychiatry",
    members: [
      { name: "Dr. Shrikant Kiran Nimbhorkar", designation: HOD },
      { name: "Dr. Amol Deepak Kelkar", designation: AS },
      { name: "Dr. Radhika Amol Kelkar", designation: AP },
      { name: "Dr. Sushrut Vinayak Patil", designation: SR },
      { name: "Dr. Ganesh Dadarao Thakare", designation: JR },
      { name: "Dr. Mahesh Sunil Kad", designation: JR },
      { name: "Dr. Nikhil Chandrakant Kanase", designation: JR },
    ],
  },
  {
    slug: "general-surgery",
    name: "General Surgery",
    members: [
      { name: "Dr. Mahendra Ramesh Chandak", designation: HOD },
      { name: "Dr. Anil Shriram Rathod", designation: P },
      { name: "Dr. Vipin Shamsundar Mundhada", designation: P },
      { name: "Dr. Ashok Kisanrao Gaikwad", designation: AS },
      { name: "Dr. Gaurav Gokulchandji Goenka", designation: AS },
      { name: "Dr. Anup Prakash Dhoran", designation: AP },
      { name: "Dr. Prashant Galsing Rathod", designation: AP },
      { name: "Dr. Mayur Bhikulal Agrawal", designation: AP },
      { name: "Dr. Shrikant Vilas Pingale", designation: AP },
      { name: "Dr. Tushar Gajananrao Morey", designation: AP },
      { name: "Dr. Ajaysingh Vijaysingh Chauhan", designation: SR },
      { name: "Dr. Ambrish Tukaram Shamkuwar", designation: SR },
      { name: "Dr. Chandrakant Bhimrao Ghuge", designation: SR },
      { name: "Dr. Gajanan Kashiram Pophale", designation: SR },
      { name: "Dr. Vishal Subhash Mandale", designation: SR },
      { name: "Dr. Ajay Subhashrao Davhale", designation: JR },
      { name: "Dr. Ashutosh Eknath Jagrut", designation: JR },
      { name: "Dr. Avinash Diliprao Sangle", designation: JR },
      { name: "Dr. Avinash Mahadeo Attarkar", designation: JR },
      { name: "Dr. Avinash Nitin Kumbhar", designation: JR },
      { name: "Dr. Nitin Vilas Jaybhaye", designation: JR },
      { name: "Dr. Rahul Keshawrao Supare", designation: JR },
      { name: "Dr. Shubham Gopal Khambalkar", designation: JR },
      { name: "Dr. Swapnil Sunil Sonune", designation: JR },
      { name: "Dr. Vaibhav Babanrao Kedar", designation: JR },
      { name: "Dr. Vijay Madhavrao Kathole", designation: JR },
      { name: "Dr. Vikrant Vitthalrao Ingle", designation: JR },
    ],
  },
  {
    slug: "orthopedics",
    name: "Orthopedics",
    members: [
      { name: "Dr. Rupam Uddhaorao Divthane", designation: HOD },
      { name: "Dr. Nikhil Pramodrao Borde", designation: AS },
      { name: "Dr. Rohan Ghanshyam Bansal", designation: AS },
      { name: "Dr. Jagdish Uttam Patil", designation: AP },
      { name: "Dr. Pranay Santoshrao Mahalle", designation: AP },
      { name: "Dr. Prashant Shivanand Janorkar", designation: AP },
      { name: "Dr. Samadhan Sarangdhar Mundhe", designation: AP },
      { name: "Dr. Amit Nanakram Rajpal", designation: SR },
      { name: "Dr. Darshan Bajrang Tatia", designation: SR },
      { name: "Dr. Dhananjay Damodhar Satpute", designation: SR },
      { name: "Dr. Aniruddha Bhanudas Mante", designation: JR },
      { name: "Dr. Mahesh Nivrutti Yeole", designation: JR },
      { name: "Dr. Milind Suresh Rathod", designation: JR },
      { name: "Dr. Shrikant Galsing Rathod", designation: JR },
    ],
  },
  {
    slug: "ent",
    name: "Otorhinolaryngology (ENT)",
    members: [
      { name: "Dr. Sanjay Ramdatta Agrawal", designation: HOD },
      { name: "Dr. Prashant Manohar Dukare", designation: AS },
      { name: "Dr. Sanjeev Shankar Narkhede", designation: AS },
      { name: "Dr. Deepak Laxman Mankar", designation: AP },
      { name: "Dr. Priyanka Pravin Dandi", designation: SR },
      { name: "Dr. Ravi Shriram Sanap", designation: SR },
      { name: "Dr. Faisal Dilavarkhan Pathan", designation: JR },
      { name: "Dr. Sachin Lala Kokate", designation: JR },
    ],
  },
  {
    slug: "ophthalmology",
    name: "Ophthalmology",
    members: [
      { name: "Dr. Pallavi Rupam Divthane", designation: HOD },
      { name: "Dr. Neha Gaurav Mantri", designation: AS },
      { name: "Dr. Priyanka Shankar Garkal", designation: AP },
      { name: "Dr. Vikrant Narwade", designation: AP },
      { name: "Dr. Gajanan Prakash Shelke", designation: SR },
      { name: "Dr. Shreyas Rajesh Lohiya", designation: SR },
      { name: "Dr. Pooja Dinkar Thakre", designation: JR },
      { name: "Dr. Sandhya Bhanudas Budhwat", designation: JR },
      { name: "Dr. Sonal Vipin Mundhada", designation: JR },
    ],
  },
  {
    slug: "obgyn",
    name: "Gynecology & Obstetrics",
    members: [
      { name: "Dr. Pramod Dhananjay Jadhav", designation: "Dean & Professor" },
      { name: "Dr. Atul Radheshyam Mundada", designation: AS },
      { name: "Dr. Vitthal Shriram Kaluse", designation: AS },
      { name: "Dr. Ashish Ramesh Tale", designation: AP },
      { name: "Dr. Leela Vitthal Karpe", designation: AP },
      { name: "Dr. Mayuri Anup Dhoran", designation: AP },
      { name: "Dr. Nilesh Mohansing Solanke", designation: AP },
      { name: "Dr. Pratiksha Krushnarao Deshmukh", designation: AP },
      { name: "Dr. Pravin Laxman Rajput", designation: AP },
      { name: "Dr. Deepika Dinesh Lalwani", designation: SR },
      { name: "Dr. Dipak Dattu Bhagat", designation: SR },
      { name: "Dr. Shubhangi Laxman Rajput", designation: SR },
      { name: "Dr. Varsha Sharad Lakhotiya", designation: SR },
      { name: "Dr. Ananta Shankarrao Gore", designation: JR },
      { name: "Dr. Gita Gajanan Shelke", designation: JR },
      { name: "Dr. Pradnya Vinayak Changade", designation: JR },
      { name: "Dr. Shyam Bhujangrao Dalvi", designation: JR },
      { name: "Dr. Suraj Patkar", designation: JR },
      { name: "Dr. Swapnil Sanjay Deshmukh", designation: JR },
    ],
  },
  {
    slug: "anesthesia",
    name: "Anesthesia",
    members: [
      { name: "Dr. Gaurav Mahendra Chhajed", designation: HOD },
      { name: "Dr. Kishor Pandurang Pachkor", designation: P },
      { name: "Dr. Kamalkishore Bhagirath Laddha", designation: P },
      { name: "Dr. Anupama Vitthal Kaluse", designation: AS },
      { name: "Dr. Anuj Anant Gawali", designation: AP },
      { name: "Dr. Bipin Narayanrao Jibhkate", designation: AP },
      { name: "Dr. Dinesh Lalchand Lalwani", designation: AP },
      { name: "Dr. Sonal Balasaheb Katrale", designation: AP },
      { name: "Dr. Suman Rohan Bansal", designation: AP },
      { name: "Dr. Nirav Mahidasbhai Bhalodia", designation: SR },
      { name: "Dr. Gayatri Deepak Vasagadekar", designation: SR },
      { name: "Dr. Mayuresh Rajiv Umalkar", designation: SR },
      { name: "Dr. Vikas Atmaram Sonwane", designation: SR },
    ],
  },
  {
    slug: "radiodiagnosis",
    name: "Radio Diagnosis",
    members: [
      { name: "Dr. Akash Madhavrao Mahalle", designation: HOD },
      { name: "Dr. Jayprakash Mitthulal Bhansali", designation: P },
      { name: "Dr. Pramod Agrawal", designation: P },
      { name: "Dr. Rohan Magan Kalamkar", designation: AS },
      { name: "Dr. Chandrakant Sitaram Jadhao", designation: AP },
      { name: "Dr. Saurabh Govind Padiya", designation: AP },
      { name: "Dr. Vivek Deshmukh", designation: AP },
      { name: "Dr. Amol Vishwanathrao Khandale", designation: SR },
      { name: "Dr. Vikas Gaikwad", designation: SR },
      { name: "Dr. Krishna Satish Saoji", designation: SR },
      { name: "Dr. Manoj Rajesh Ambhure", designation: SR },
      { name: "Dr. Yogesh Shaligram Rathod", designation: SR },
    ],
  },
  {
    slug: "dentistry",
    name: "Dentistry",
    members: [
      { name: "Dr. Rushikesh Vinayak Kadu", designation: AS },
      { name: "Dr. Kiran Manikrao Dhakarge", designation: AP },
      { name: "Dr. Saurabh Sureshrao Ghuge", designation: SR },
      { name: "Dr. Vijay Wasudeo Sharma", designation: SR },
      { name: "Dr. Vrushali Madhavrao Kathole", designation: SR },
    ],
  },
];

export const TEACHING_STAFF_COUNT = TEACHING_STAFF.reduce(
  (n, d) => n + d.members.length,
  0,
);

export function staffForDepartment(slug: string): StaffMember[] {
  return TEACHING_STAFF.find((d) => d.slug === slug)?.members ?? [];
}
