-- Seed the faculty table from the official teaching-staff list.
-- Supabase Dashboard -> SQL Editor -> paste -> Run. (Re-runnable.)

delete from public.faculty;

insert into public.faculty (name, designation, department, sort_order) values
  ('Dr. Dhannya Binoy', 'Professor & HOD', 'Anatomy', 1),
  ('Dr. Kalpana Rajendra Gaikwad', 'Associate Professor', 'Anatomy', 2),
  ('Dr. Salahuddin Azeemuddin Patel', 'Associate Professor', 'Anatomy', 3),
  ('Dr. Monika Soni', 'Assistant Professor', 'Anatomy', 4),
  ('Dr. Saikarthik J', 'Assistant Professor', 'Anatomy', 5),
  ('Dr. Ankit Purushottam Biyani', 'Tutor', 'Anatomy', 6),
  ('Dr. Arun Subhash Jain', 'Tutor', 'Anatomy', 7),
  ('Dr. Arvind Asaram Aghao', 'Tutor', 'Anatomy', 8),
  ('Dr. Narendra Sanjay Sarode', 'Tutor', 'Anatomy', 9),
  ('Dr. Nitin Bansi Jadhao', 'Tutor', 'Anatomy', 10),
  ('Dr. Prashant Ramnath Kanade', 'Tutor', 'Anatomy', 11),
  ('Dr. Shubham Parmeshwar Chaudhari', 'Tutor', 'Anatomy', 12),
  ('Dr. Vaibhav Shivaji Akangire', 'Tutor', 'Anatomy', 13),
  ('Dr. Shivani Dattatray Yewale', 'Tutor', 'Anatomy', 14),
  ('Dr. Barkat Ali Abdul Ali Thobani', 'Professor & HOD', 'Physiology', 15),
  ('Dr. Neelima Jaykumar Bhandarkar', 'Professor', 'Physiology', 16),
  ('Dr. Priya Nitin Samal', 'Associate Professor', 'Physiology', 17),
  ('Dr. Saraswathi', 'Assistant Professor', 'Physiology', 18),
  ('Dr. Sneha Vitthal Chopade', 'Assistant Professor', 'Physiology', 19),
  ('Dr. Akshay Gajanan Ulhamale', 'Tutor', 'Physiology', 20),
  ('Dr. Ashwin Vijay Chamediya', 'Tutor', 'Physiology', 21),
  ('Dr. Gunwant Shankar Shelke', 'Tutor', 'Physiology', 22),
  ('Dr. Komal Dhanraj Rathi', 'Tutor', 'Physiology', 23),
  ('Dr. Gaurav Gajanan Lonkar', 'Tutor', 'Physiology', 24),
  ('Dr. Nikhil Gajanan Gite', 'Tutor', 'Physiology', 25),
  ('Dr. Prashant Ajay Ingle', 'Tutor', 'Physiology', 26),
  ('Dr. Sapana Mahendra Chandak', 'Tutor', 'Physiology', 27),
  ('Dr. Srushtee Bipin Jibhkate', 'Professor & HOD', 'Bio Chemistry', 28),
  ('Dr. Amit Hiralal Asalkar', 'Associate Professor', 'Bio Chemistry', 29),
  ('Dr. Chiruvella Sravani', 'Assistant Professor', 'Bio Chemistry', 30),
  ('Dr. Seema Akhil Agarwal', 'Assistant Professor', 'Bio Chemistry', 31),
  ('Dr. Chetan Mahadeo Satote', 'Tutor', 'Bio Chemistry', 32),
  ('Dr. Gopal Dinesh Nawgaje', 'Tutor', 'Bio Chemistry', 33),
  ('Dr. Prathamesh Ramesh Akhare', 'Tutor', 'Bio Chemistry', 34),
  ('Dr. Pratiksha Ambadas Aghao', 'Tutor', 'Bio Chemistry', 35),
  ('Dr. Sakshi Sushil Rathi', 'Tutor', 'Bio Chemistry', 36),
  ('Dr. Shraddha Mayur Agrawal', 'Tutor', 'Bio Chemistry', 37),
  ('Dr. Yogita Panjab Shejol', 'Tutor', 'Bio Chemistry', 38),
  ('Dr. Mayuri Nikhil Mahajan', 'Professor', 'MicroBiology', 39),
  ('Dr. Anjali Lalit Raut', 'Associate Professor', 'MicroBiology', 40),
  ('Dr. Sonali Mangesh Choudhari', 'Associate Professor', 'MicroBiology', 41),
  ('Dr. Pankaj Vishwakarma', 'Assistant Professor', 'MicroBiology', 42),
  ('Dr. Rutuja Avinash Dongare', 'Assistant Professor', 'MicroBiology', 43),
  ('Dr. Vidya Nagesh Bhosale', 'Assistant Professor', 'MicroBiology', 44),
  ('Dr. Suvarna Samir Bhopale', 'Tutor', 'MicroBiology', 45),
  ('Dr. Madhvik Sanjay Lohiya', 'Tutor', 'MicroBiology', 46),
  ('Dr. Om Vijay Lahane', 'Tutor', 'MicroBiology', 47),
  ('Dr. Nikhil Shridhar Jaybhaye', 'Tutor', 'MicroBiology', 48),
  ('Dr. Rohit Ramesh Patil', 'Tutor', 'MicroBiology', 49),
  ('Dr. Pratiksha Nagsen Wankhade', 'Tutor', 'MicroBiology', 50),
  ('Dr. Shruti Vikas Shinde', 'Tutor', 'MicroBiology', 51),
  ('Dr. Vivek Lal', 'Professor', 'Pharmacology', 52),
  ('Dr. Chetan Shankarrao Urade', 'Associate Professor', 'Pharmacology', 53),
  ('Dr. Rahul Tilakchand Khobragade', 'Associate Professor', 'Pharmacology', 54),
  ('Dr. Akhil Bharat Agarwal', 'Assistant Professor', 'Pharmacology', 55),
  ('Dr. Arpit Vallabhbhai Vachhani', 'Assistant Professor', 'Pharmacology', 56),
  ('Dr. Florence Bhava', 'Assistant Professor', 'Pharmacology', 57),
  ('Dr. Nilesh Shivaji Kute', 'Tutor', 'Pharmacology', 58),
  ('Dr. Nitin Prakash Sanap', 'Tutor', 'Pharmacology', 59),
  ('Dr. Rameshwar Balaji Dalvi', 'Tutor', 'Pharmacology', 60),
  ('Dr. Rushikesh Sudhakar Lahane', 'Tutor', 'Pharmacology', 61),
  ('Dr. Santosh Kalyanrao Gawade', 'Tutor', 'Pharmacology', 62),
  ('Dr. Shubham Uddhav Nagre', 'Tutor', 'Pharmacology', 63),
  ('Dr. Vaibhav Subhash Shinde', 'Tutor', 'Pharmacology', 64),
  ('Dr. Suchita Chetan Padia', 'Professor & HOD', 'Pathology', 65),
  ('Dr. Anandkumar Chordiya', 'Associate Professor', 'Pathology', 66),
  ('Dr. Bramhananda Ramrao Tale', 'Associate Professor', 'Pathology', 67),
  ('Dr. Preethi Tushar Charkha', 'Associate Professor', 'Pathology', 68),
  ('Dr. Dnyaneshwar Ashok Doifode', 'Assistant Professor', 'Pathology', 69),
  ('Dr. Kavita Yogesh Kolamkar', 'Assistant Professor', 'Pathology', 70),
  ('Dr. Shyamkumar Haribhau Nemade', 'Assistant Professor', 'Pathology', 71),
  ('Dr. Pratibha Tejrao Shinde', 'Senior Resident', 'Pathology', 72),
  ('Dr. Shwetali Ramesh Akhare', 'Senior Resident', 'Pathology', 73),
  ('Dr. Snehal Rameshsing Rajput', 'Senior Resident', 'Pathology', 74),
  ('Dr. Akshay Anandrao Dolarkar', 'Tutor', 'Pathology', 75),
  ('Dr. Sanket Keshaorao Nagre', 'Tutor', 'Pathology', 76),
  ('Dr. Shruti Sagar Idhol', 'Tutor', 'Pathology', 77),
  ('Dr. Vaishnavi Dinkar Rathod', 'Tutor', 'Pathology', 78),
  ('Dr. Vikas Anandrao Nagargoje', 'Tutor', 'Pathology', 79),
  ('Dr. Prashil Prakashrao Jumade', 'Professor & HOD', 'PSM (Community Medicine)', 80),
  ('Dr. Gokul Kumar K', 'Associate Professor', 'PSM (Community Medicine)', 81),
  ('Dr. Swapnil Wamanrao Malkhede', 'Associate Professor', 'PSM (Community Medicine)', 82),
  ('Dr. Saniya Sk. Shafi Qureshi', 'Assistant Professor', 'PSM (Community Medicine)', 83),
  ('Dr. Sunil Marutirao Bhadkumbe', 'Assistant Professor', 'PSM (Community Medicine)', 84),
  ('Dr. Amol Gowardhan Dakhare', 'Statistician', 'PSM (Community Medicine)', 85),
  ('Dr. Ambarish Ghansham Mandhane', 'Tutor', 'PSM (Community Medicine)', 86),
  ('Dr. Ashish Gajanan Khandare', 'Tutor', 'PSM (Community Medicine)', 87),
  ('Dr. Atul Girdharilal Singhania', 'Tutor', 'PSM (Community Medicine)', 88),
  ('Dr. Atul Sureshrao Junghare', 'Tutor', 'PSM (Community Medicine)', 89),
  ('Dr. Sarvesh Pravin Bhansali', 'Tutor', 'PSM (Community Medicine)', 90),
  ('Dr. Umesh Narsing Jadhao', 'Tutor', 'PSM (Community Medicine)', 91),
  ('Dr. Shailendra Hemant Anande', 'Associate Professor', 'Forensic Medicine (FMT)', 92),
  ('Dr. Purushottam Madhukar Khade', 'Assistant Professor', 'Forensic Medicine (FMT)', 93),
  ('Dr. Akshay Madhusudan Toshniwal', 'Tutor', 'Forensic Medicine (FMT)', 94),
  ('Dr. Ashutosh Vijay Deshmukh', 'Tutor', 'Forensic Medicine (FMT)', 95),
  ('Dr. Pranali Madhusudan Toshniwal', 'Tutor', 'Forensic Medicine (FMT)', 96),
  ('Dr. Prashant Ramkrushn Wayal', 'Tutor', 'Forensic Medicine (FMT)', 97),
  ('Dr. Saurav Gajanan Tale', 'Tutor', 'Forensic Medicine (FMT)', 98),
  ('Dr. Shubham Shriram Ingle', 'Tutor', 'Forensic Medicine (FMT)', 99),
  ('Dr. Shankar Baliram Wankhade', 'Professor & HOD', 'General Medicine', 100),
  ('Dr. Yuvraj Vasantrao Mhaske', 'Professor', 'General Medicine', 101),
  ('Dr. Amit Chandrakant Rathi', 'Associate Professor', 'General Medicine', 102),
  ('Dr. Bharat Murlidhar Pangole', 'Associate Professor', 'General Medicine', 103),
  ('Dr. Santosh Suresh Saoji', 'Associate Professor', 'General Medicine', 104),
  ('Dr. Ashish Janardan Changade', 'Assistant Professor', 'General Medicine', 105),
  ('Dr. Harish Ramesh Darak', 'Assistant Professor', 'General Medicine', 106),
  ('Dr. Mahesh Ramdas Ohar', 'Assistant Professor', 'General Medicine', 107),
  ('Dr. Sagar Ravindra Idhol', 'Assistant Professor', 'General Medicine', 108),
  ('Dr. Yogesh Gajanan Kolamkar', 'Assistant Professor', 'General Medicine', 109),
  ('Dr. Yogeshwar Sureshrao Mukund', 'Assistant Professor', 'General Medicine', 110),
  ('Dr. Amol Bhagwanrao Khavane', 'Senior Resident', 'General Medicine', 111),
  ('Dr. Dhananjay Samadhan Marode', 'Senior Resident', 'General Medicine', 112),
  ('Dr. Swapnil Dinkar Sarode', 'Senior Resident', 'General Medicine', 113),
  ('Dr. Tushar Kamalkishor Charkha', 'Senior Resident', 'General Medicine', 114),
  ('Dr. Akshay Dnyanba Gilwarkar', 'Junior Resident', 'General Medicine', 115),
  ('Dr. Ashwin Manohar Khandare', 'Junior Resident', 'General Medicine', 116),
  ('Dr. Bhushan Pravin Mallawat', 'Junior Resident', 'General Medicine', 117),
  ('Dr. Ruturaj Narayan Nagargoje', 'Junior Resident', 'General Medicine', 118),
  ('Dr. Neeraj Sanjay Thakur', 'Junior Resident', 'General Medicine', 119),
  ('Dr. Pranav Sanjay Salunke', 'Junior Resident', 'General Medicine', 120),
  ('Dr. Prashant Vishnu Tejankar', 'Junior Resident', 'General Medicine', 121),
  ('Dr. Pravin Vaijinath Parne', 'Junior Resident', 'General Medicine', 122),
  ('Dr. Rahul Gajananrao Sonune', 'Junior Resident', 'General Medicine', 123),
  ('Dr. Shantanu Diliprao Joshi', 'Junior Resident', 'General Medicine', 124),
  ('Dr. Tushar Vijay Pandav', 'Junior Resident', 'General Medicine', 125),
  ('Dr. Vaibhav Sukhadeo Thakare', 'Junior Resident', 'General Medicine', 126),
  ('Dr. Vinit Panditrao Deshmukh', 'Junior Resident', 'General Medicine', 127),
  ('Dr. Chetan Bhagwandas Padia', 'Professor & HOD', 'Pediatrics', 128),
  ('Dr. Nikhil Madhav Mahajan', 'Professor', 'Pediatrics', 129),
  ('Dr. Vishwanath Narayan Dighole', 'Associate Professor', 'Pediatrics', 130),
  ('Dr. Anil Rajendra Tapdiya', 'Assistant Professor', 'Pediatrics', 131),
  ('Dr. Bhagyashree Macchindra Jagtap', 'Assistant Professor', 'Pediatrics', 132),
  ('Dr. Shailee Rasikchandra Patel', 'Assistant Professor', 'Pediatrics', 133),
  ('Dr. Mansi Shah', 'Assistant Professor', 'Pediatrics', 134),
  ('Dr. Shailesh Dilip Jain', 'Assistant Professor', 'Pediatrics', 135),
  ('Dr. Abolee Jalandar Pansare', 'Senior Resident', 'Pediatrics', 136),
  ('Dr. Amit Shantilal Bora', 'Senior Resident', 'Pediatrics', 137),
  ('Dr. Ashish Hanwantrao Narwade', 'Senior Resident', 'Pediatrics', 138),
  ('Dr. Samir Ashokrao Bhopale', 'Senior Resident', 'Pediatrics', 139),
  ('Dr. Nilesh Ashok Sanap', 'Senior Resident', 'Pediatrics', 140),
  ('Dr. Pravin Khushalrao Gawai', 'Senior Resident', 'Pediatrics', 141),
  ('Dr. Sharad Shamsundar Lakhotiya', 'Senior Resident', 'Pediatrics', 142),
  ('Dr. Vinayak Shivaji Changade', 'Senior Resident', 'Pediatrics', 143),
  ('Dr. Vinod Kishor Ramchandani', 'Senior Resident', 'Pediatrics', 144),
  ('Dr. Vivek Chandrashekhar Kapse', 'Senior Resident', 'Pediatrics', 145),
  ('Dr. Aniket Rameshwar Kewat', 'Junior Resident', 'Pediatrics', 146),
  ('Dr. Rajesh Omprakash Kedia', 'Professor & HOD', 'Dermatology (Skin / DVL)', 147),
  ('Dr. Sagar Subhash Taley', 'Associate Professor', 'Dermatology (Skin / DVL)', 148),
  ('Dr. Areha Jain', 'Assistant Professor', 'Dermatology (Skin / DVL)', 149),
  ('Dr. Saurabh Santosh Sarda', 'Assistant Professor', 'Dermatology (Skin / DVL)', 150),
  ('Dr. Shivani Munnalal Agrawal', 'Senior Resident', 'Dermatology (Skin / DVL)', 151),
  ('Dr. Yogeshree Nikhil Kanase', 'Senior Resident', 'Dermatology (Skin / DVL)', 152),
  ('Dr. Surekha Pramod Jadhav', 'Junior Resident', 'Dermatology (Skin / DVL)', 153),
  ('Dr. Shrikant Kiran Nimbhorkar', 'Professor & HOD', 'Psychiatry', 154),
  ('Dr. Amol Deepak Kelkar', 'Associate Professor', 'Psychiatry', 155),
  ('Dr. Radhika Amol Kelkar', 'Assistant Professor', 'Psychiatry', 156),
  ('Dr. Sushrut Vinayak Patil', 'Senior Resident', 'Psychiatry', 157),
  ('Dr. Ganesh Dadarao Thakare', 'Junior Resident', 'Psychiatry', 158),
  ('Dr. Mahesh Sunil Kad', 'Junior Resident', 'Psychiatry', 159),
  ('Dr. Nikhil Chandrakant Kanase', 'Junior Resident', 'Psychiatry', 160),
  ('Dr. Mahendra Ramesh Chandak', 'Professor & HOD', 'General Surgery', 161),
  ('Dr. Anil Shriram Rathod', 'Professor', 'General Surgery', 162),
  ('Dr. Vipin Shamsundar Mundhada', 'Professor', 'General Surgery', 163),
  ('Dr. Ashok Kisanrao Gaikwad', 'Associate Professor', 'General Surgery', 164),
  ('Dr. Gaurav Gokulchandji Goenka', 'Associate Professor', 'General Surgery', 165),
  ('Dr. Anup Prakash Dhoran', 'Assistant Professor', 'General Surgery', 166),
  ('Dr. Prashant Galsing Rathod', 'Assistant Professor', 'General Surgery', 167),
  ('Dr. Mayur Bhikulal Agrawal', 'Assistant Professor', 'General Surgery', 168),
  ('Dr. Shrikant Vilas Pingale', 'Assistant Professor', 'General Surgery', 169),
  ('Dr. Tushar Gajananrao Morey', 'Assistant Professor', 'General Surgery', 170),
  ('Dr. Ajaysingh Vijaysingh Chauhan', 'Senior Resident', 'General Surgery', 171),
  ('Dr. Ambrish Tukaram Shamkuwar', 'Senior Resident', 'General Surgery', 172),
  ('Dr. Chandrakant Bhimrao Ghuge', 'Senior Resident', 'General Surgery', 173),
  ('Dr. Gajanan Kashiram Pophale', 'Senior Resident', 'General Surgery', 174),
  ('Dr. Vishal Subhash Mandale', 'Senior Resident', 'General Surgery', 175),
  ('Dr. Ajay Subhashrao Davhale', 'Junior Resident', 'General Surgery', 176),
  ('Dr. Ashutosh Eknath Jagrut', 'Junior Resident', 'General Surgery', 177),
  ('Dr. Avinash Diliprao Sangle', 'Junior Resident', 'General Surgery', 178),
  ('Dr. Avinash Mahadeo Attarkar', 'Junior Resident', 'General Surgery', 179),
  ('Dr. Avinash Nitin Kumbhar', 'Junior Resident', 'General Surgery', 180),
  ('Dr. Nitin Vilas Jaybhaye', 'Junior Resident', 'General Surgery', 181),
  ('Dr. Rahul Keshawrao Supare', 'Junior Resident', 'General Surgery', 182),
  ('Dr. Shubham Gopal Khambalkar', 'Junior Resident', 'General Surgery', 183),
  ('Dr. Swapnil Sunil Sonune', 'Junior Resident', 'General Surgery', 184),
  ('Dr. Vaibhav Babanrao Kedar', 'Junior Resident', 'General Surgery', 185),
  ('Dr. Vijay Madhavrao Kathole', 'Junior Resident', 'General Surgery', 186),
  ('Dr. Vikrant Vitthalrao Ingle', 'Junior Resident', 'General Surgery', 187),
  ('Dr. Rupam Uddhaorao Divthane', 'Professor & HOD', 'Orthopedics', 188),
  ('Dr. Nikhil Pramodrao Borde', 'Associate Professor', 'Orthopedics', 189),
  ('Dr. Rohan Ghanshyam Bansal', 'Associate Professor', 'Orthopedics', 190),
  ('Dr. Jagdish Uttam Patil', 'Assistant Professor', 'Orthopedics', 191),
  ('Dr. Pranay Santoshrao Mahalle', 'Assistant Professor', 'Orthopedics', 192),
  ('Dr. Prashant Shivanand Janorkar', 'Assistant Professor', 'Orthopedics', 193),
  ('Dr. Samadhan Sarangdhar Mundhe', 'Assistant Professor', 'Orthopedics', 194),
  ('Dr. Amit Nanakram Rajpal', 'Senior Resident', 'Orthopedics', 195),
  ('Dr. Darshan Bajrang Tatia', 'Senior Resident', 'Orthopedics', 196),
  ('Dr. Dhananjay Damodhar Satpute', 'Senior Resident', 'Orthopedics', 197),
  ('Dr. Aniruddha Bhanudas Mante', 'Junior Resident', 'Orthopedics', 198),
  ('Dr. Mahesh Nivrutti Yeole', 'Junior Resident', 'Orthopedics', 199),
  ('Dr. Milind Suresh Rathod', 'Junior Resident', 'Orthopedics', 200),
  ('Dr. Shrikant Galsing Rathod', 'Junior Resident', 'Orthopedics', 201),
  ('Dr. Sanjay Ramdatta Agrawal', 'Professor & HOD', 'Otorhinolaryngology (ENT)', 202),
  ('Dr. Prashant Manohar Dukare', 'Associate Professor', 'Otorhinolaryngology (ENT)', 203),
  ('Dr. Sanjeev Shankar Narkhede', 'Associate Professor', 'Otorhinolaryngology (ENT)', 204),
  ('Dr. Deepak Laxman Mankar', 'Assistant Professor', 'Otorhinolaryngology (ENT)', 205),
  ('Dr. Priyanka Pravin Dandi', 'Senior Resident', 'Otorhinolaryngology (ENT)', 206),
  ('Dr. Ravi Shriram Sanap', 'Senior Resident', 'Otorhinolaryngology (ENT)', 207),
  ('Dr. Faisal Dilavarkhan Pathan', 'Junior Resident', 'Otorhinolaryngology (ENT)', 208),
  ('Dr. Sachin Lala Kokate', 'Junior Resident', 'Otorhinolaryngology (ENT)', 209),
  ('Dr. Pallavi Rupam Divthane', 'Professor & HOD', 'Ophthalmology', 210),
  ('Dr. Neha Gaurav Mantri', 'Associate Professor', 'Ophthalmology', 211),
  ('Dr. Priyanka Shankar Garkal', 'Assistant Professor', 'Ophthalmology', 212),
  ('Dr. Vikrant Narwade', 'Assistant Professor', 'Ophthalmology', 213),
  ('Dr. Gajanan Prakash Shelke', 'Senior Resident', 'Ophthalmology', 214),
  ('Dr. Shreyas Rajesh Lohiya', 'Senior Resident', 'Ophthalmology', 215),
  ('Dr. Pooja Dinkar Thakre', 'Junior Resident', 'Ophthalmology', 216),
  ('Dr. Sandhya Bhanudas Budhwat', 'Junior Resident', 'Ophthalmology', 217),
  ('Dr. Sonal Vipin Mundhada', 'Junior Resident', 'Ophthalmology', 218),
  ('Dr. Pramod Dhananjay Jadhav', 'Dean & Professor', 'Gynecology & Obstetrics', 219),
  ('Dr. Atul Radheshyam Mundada', 'Associate Professor', 'Gynecology & Obstetrics', 220),
  ('Dr. Vitthal Shriram Kaluse', 'Associate Professor', 'Gynecology & Obstetrics', 221),
  ('Dr. Ashish Ramesh Tale', 'Assistant Professor', 'Gynecology & Obstetrics', 222),
  ('Dr. Leela Vitthal Karpe', 'Assistant Professor', 'Gynecology & Obstetrics', 223),
  ('Dr. Mayuri Anup Dhoran', 'Assistant Professor', 'Gynecology & Obstetrics', 224),
  ('Dr. Nilesh Mohansing Solanke', 'Assistant Professor', 'Gynecology & Obstetrics', 225),
  ('Dr. Pratiksha Krushnarao Deshmukh', 'Assistant Professor', 'Gynecology & Obstetrics', 226),
  ('Dr. Pravin Laxman Rajput', 'Assistant Professor', 'Gynecology & Obstetrics', 227),
  ('Dr. Deepika Dinesh Lalwani', 'Senior Resident', 'Gynecology & Obstetrics', 228),
  ('Dr. Dipak Dattu Bhagat', 'Senior Resident', 'Gynecology & Obstetrics', 229),
  ('Dr. Shubhangi Laxman Rajput', 'Senior Resident', 'Gynecology & Obstetrics', 230),
  ('Dr. Varsha Sharad Lakhotiya', 'Senior Resident', 'Gynecology & Obstetrics', 231),
  ('Dr. Ananta Shankarrao Gore', 'Junior Resident', 'Gynecology & Obstetrics', 232),
  ('Dr. Gita Gajanan Shelke', 'Junior Resident', 'Gynecology & Obstetrics', 233),
  ('Dr. Pradnya Vinayak Changade', 'Junior Resident', 'Gynecology & Obstetrics', 234),
  ('Dr. Shyam Bhujangrao Dalvi', 'Junior Resident', 'Gynecology & Obstetrics', 235),
  ('Dr. Suraj Patkar', 'Junior Resident', 'Gynecology & Obstetrics', 236),
  ('Dr. Swapnil Sanjay Deshmukh', 'Junior Resident', 'Gynecology & Obstetrics', 237),
  ('Dr. Gaurav Mahendra Chhajed', 'Professor & HOD', 'Anesthesia', 238),
  ('Dr. Kishor Pandurang Pachkor', 'Professor', 'Anesthesia', 239),
  ('Dr. Kamalkishore Bhagirath Laddha', 'Professor', 'Anesthesia', 240),
  ('Dr. Anupama Vitthal Kaluse', 'Associate Professor', 'Anesthesia', 241),
  ('Dr. Anuj Anant Gawali', 'Assistant Professor', 'Anesthesia', 242),
  ('Dr. Bipin Narayanrao Jibhkate', 'Assistant Professor', 'Anesthesia', 243),
  ('Dr. Dinesh Lalchand Lalwani', 'Assistant Professor', 'Anesthesia', 244),
  ('Dr. Sonal Balasaheb Katrale', 'Assistant Professor', 'Anesthesia', 245),
  ('Dr. Suman Rohan Bansal', 'Assistant Professor', 'Anesthesia', 246),
  ('Dr. Nirav Mahidasbhai Bhalodia', 'Senior Resident', 'Anesthesia', 247),
  ('Dr. Gayatri Deepak Vasagadekar', 'Senior Resident', 'Anesthesia', 248),
  ('Dr. Mayuresh Rajiv Umalkar', 'Senior Resident', 'Anesthesia', 249),
  ('Dr. Vikas Atmaram Sonwane', 'Senior Resident', 'Anesthesia', 250),
  ('Dr. Akash Madhavrao Mahalle', 'Professor & HOD', 'Radio Diagnosis', 251),
  ('Dr. Jayprakash Mitthulal Bhansali', 'Professor', 'Radio Diagnosis', 252),
  ('Dr. Pramod Agrawal', 'Professor', 'Radio Diagnosis', 253),
  ('Dr. Rohan Magan Kalamkar', 'Associate Professor', 'Radio Diagnosis', 254),
  ('Dr. Chandrakant Sitaram Jadhao', 'Assistant Professor', 'Radio Diagnosis', 255),
  ('Dr. Saurabh Govind Padiya', 'Assistant Professor', 'Radio Diagnosis', 256),
  ('Dr. Vivek Deshmukh', 'Assistant Professor', 'Radio Diagnosis', 257),
  ('Dr. Amol Vishwanathrao Khandale', 'Senior Resident', 'Radio Diagnosis', 258),
  ('Dr. Vikas Gaikwad', 'Senior Resident', 'Radio Diagnosis', 259),
  ('Dr. Krishna Satish Saoji', 'Senior Resident', 'Radio Diagnosis', 260),
  ('Dr. Manoj Rajesh Ambhure', 'Senior Resident', 'Radio Diagnosis', 261),
  ('Dr. Yogesh Shaligram Rathod', 'Senior Resident', 'Radio Diagnosis', 262),
  ('Dr. Rushikesh Vinayak Kadu', 'Associate Professor', 'Dentistry', 263),
  ('Dr. Kiran Manikrao Dhakarge', 'Assistant Professor', 'Dentistry', 264),
  ('Dr. Saurabh Sureshrao Ghuge', 'Senior Resident', 'Dentistry', 265),
  ('Dr. Vijay Wasudeo Sharma', 'Senior Resident', 'Dentistry', 266),
  ('Dr. Vrushali Madhavrao Kathole', 'Senior Resident', 'Dentistry', 267);
